/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface ReadAlong {
    /**
    * The alignment as SMIL
    */
    'alignment': string;
    /**
    * The audio file
    */
    'audio': string;
    /**
    * Image
    */
    'image': string;
    /**
    * The text as TEI
    */
    'text': string;
  }
  interface ReadAlongAttributes extends StencilHTMLAttributes {
    /**
    * The alignment as SMIL
    */
    'alignment'?: string;
    /**
    * The audio file
    */
    'audio'?: string;
    /**
    * Image
    */
    'image'?: string;
    /**
    * The text as TEI
    */
    'text'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ReadAlong': Components.ReadAlong;
  }

  interface StencilIntrinsicElements {
    'read-along': Components.ReadAlongAttributes;
  }


  interface HTMLReadAlongElement extends Components.ReadAlong, HTMLStencilElement {}
  var HTMLReadAlongElement: {
    prototype: HTMLReadAlongElement;
    new (): HTMLReadAlongElement;
  };

  interface HTMLElementTagNameMap {
    'read-along': HTMLReadAlongElement
  }

  interface ElementTagNameMap {
    'read-along': HTMLReadAlongElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
