/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface ReadAlong {
    /**
    * The alignment as SMIL
    */
    'alignment': string;
    /**
    * The audio file
    */
    'audio': string;
    /**
    * Language
    */
    'language': string;
    /**
    * Overlay This is an SVG overlay to place over the progress bar
    */
    'svg_overlay': string;
    /**
    * ********** PROPS   * ********** The text as TEI
    */
    'text': string;
    /**
    * Theme to use: ['light', 'dark'] defaults to 'dark'
    */
    'theme': string;
  }
  interface ReadAlongAttributes extends StencilHTMLAttributes {
    /**
    * The alignment as SMIL
    */
    'alignment'?: string;
    /**
    * The audio file
    */
    'audio'?: string;
    /**
    * Language
    */
    'language'?: string;
    /**
    * Overlay This is an SVG overlay to place over the progress bar
    */
    'svg_overlay'?: string;
    /**
    * ********** PROPS   * ********** The text as TEI
    */
    'text'?: string;
    /**
    * Theme to use: ['light', 'dark'] defaults to 'dark'
    */
    'theme'?: string;
  }

  interface ReadAlongControls {
    'name': string;
  }
  interface ReadAlongControlsAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface ReadAlongProgress {
    'name': string;
  }
  interface ReadAlongProgressAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface ReadAlongText {
    'name': string;
  }
  interface ReadAlongTextAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ReadAlong': Components.ReadAlong;
    'ReadAlongControls': Components.ReadAlongControls;
    'ReadAlongProgress': Components.ReadAlongProgress;
    'ReadAlongText': Components.ReadAlongText;
  }

  interface StencilIntrinsicElements {
    'read-along': Components.ReadAlongAttributes;
    'read-along-controls': Components.ReadAlongControlsAttributes;
    'read-along-progress': Components.ReadAlongProgressAttributes;
    'read-along-text': Components.ReadAlongTextAttributes;
  }


  interface HTMLReadAlongElement extends Components.ReadAlong, HTMLStencilElement {}
  var HTMLReadAlongElement: {
    prototype: HTMLReadAlongElement;
    new (): HTMLReadAlongElement;
  };

  interface HTMLReadAlongControlsElement extends Components.ReadAlongControls, HTMLStencilElement {}
  var HTMLReadAlongControlsElement: {
    prototype: HTMLReadAlongControlsElement;
    new (): HTMLReadAlongControlsElement;
  };

  interface HTMLReadAlongProgressElement extends Components.ReadAlongProgress, HTMLStencilElement {}
  var HTMLReadAlongProgressElement: {
    prototype: HTMLReadAlongProgressElement;
    new (): HTMLReadAlongProgressElement;
  };

  interface HTMLReadAlongTextElement extends Components.ReadAlongText, HTMLStencilElement {}
  var HTMLReadAlongTextElement: {
    prototype: HTMLReadAlongTextElement;
    new (): HTMLReadAlongTextElement;
  };

  interface HTMLElementTagNameMap {
    'read-along': HTMLReadAlongElement
    'read-along-controls': HTMLReadAlongControlsElement
    'read-along-progress': HTMLReadAlongProgressElement
    'read-along-text': HTMLReadAlongTextElement
  }

  interface ElementTagNameMap {
    'read-along': HTMLReadAlongElement;
    'read-along-controls': HTMLReadAlongControlsElement;
    'read-along-progress': HTMLReadAlongProgressElement;
    'read-along-text': HTMLReadAlongTextElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
